// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"stori/helpers"
	"stori/internal/core/usecases"
	"stori/internal/handlers"
	"stori/internal/repositories"
)

// Injectors from wire.go:

func InitializeApp() *App {
	httpServiceParams := handlers.ProvideHttpServiceParams()
	databaseParameters := helpers.ProvideDatabaseParameters()
	db := helpers.ProvideDatabase(databaseParameters)
	transactionRepository := adapters.ProvideTransactionRepository(db)
	transactionUseCase := usecases.ProvideTransactionUseCase(transactionRepository)
	transactionHttpHandler := handlers.ProvideTransactionHttpHandler(transactionUseCase)
	router := handlers.ProvideRouter(transactionHttpHandler)
	httpService := handlers.ProvideHttpService(httpServiceParams, router)
	app := ProvideApp(httpService)
	return app
}
